#端口号
server:
  port: 8084

spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_seckill
    username: root
    password: 123456789
#  redis
#  redis:
#    host: 1.92.80.176
#    port: 6379

#开启驼峰式属性自动映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true

